apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-simulation-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: devops-simulation-app
  template:
    metadata:
      labels:
        app: devops-simulation-app
    spec:
      containers:
      - name: devops-simulation-app
        image: devops-simulation-app
        ports:
        - containerPort: 5000