apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-simulation
spec:
  replicas: 3
  selector:
    matchLabels:
      app: devops-simulation
  template:
    metadata:
      labels:
        app: devops-simulation
    spec:
      containers:
      - name: devops-simulation
        image: devops-simulation
        ports:
        - containerPort: 5000